package org.rsmod.content.other.devhub

import org.rsmod.api.config.refs.params
import org.rsmod.game.type.obj.ObjTypeList
import org.rsmod.map.CoordGrid

/** A single teleport destination shown in the hub's teleport menus. */
data class DevHubTeleport(val label: String, val coords: CoordGrid)

/** A named group of teleports - one spellbook, or one teleport item. */
data class DevHubTeleportGroup(val label: String, val teleports: List<DevHubTeleport>)

/**
 * Builds the hub's teleport menus, one per Teleports-tab category row.
 *
 * Spellbook destinations are not hand-authored: `SpellObjs` (api/spells) stamps every teleport
 * spell obj with `params.spell_telecoord`, so the groups are generated by scanning the cache for
 * that param and grouping by `params.spell_spellbook` (0=standard, 1=ancients, 2=lunars,
 * 3=arceuus). Only the four home teleports lack the param and are hand-entered, as are the
 * item-teleport tables (no content implements jewellery teleports yet - see the session plan).
 */
class DevHubTeleports(private val objTypes: ObjTypeList) {
    private val spellbooks: List<DevHubTeleportGroup> by lazy { buildSpellbooks() }

    /**
     * The jewellery/item destinations as one `"Group: Destination"` list (~28 entries, safely under
     * the menu's 127-choice cap) - a single category row shared by all teleport items.
     */
    private val itemsFlattened: List<DevHubTeleport> by lazy {
        ITEM_TELEPORTS.flatMap { group ->
            group.teleports.map { DevHubTeleport("${group.label}: ${it.label}", it.coords) }
        }
    }

    /** Destinations behind a Teleports-tab category row; null for any other category. */
    fun forCategory(category: DevHubCategory): List<DevHubTeleport>? =
        when (category) {
            DevHubCategory.StandardSpellbook -> spellbooks[0].teleports
            DevHubCategory.AncientSpellbook -> spellbooks[1].teleports
            DevHubCategory.LunarSpellbook -> spellbooks[2].teleports
            DevHubCategory.ArceuusSpellbook -> spellbooks[3].teleports
            DevHubCategory.JewelleryAndItems -> itemsFlattened
            else -> null
        }

    private fun buildSpellbooks(): List<DevHubTeleportGroup> {
        val byBook = mutableMapOf<Int, MutableList<Pair<Int, DevHubTeleport>>>()
        for (type in objTypes.values) {
            val coords = type.paramOrNull(params.spell_telecoord) ?: continue
            val label = type.paramOrNull(params.spell_name) ?: type.name
            val level = type.paramOrNull(params.spell_levelreq) ?: 0
            val book = type.paramOrNull(params.spell_spellbook) ?: 0
            byBook.getOrPut(book) { mutableListOf() } += level to DevHubTeleport(label, coords)
        }
        return SPELLBOOKS.map { (book, name, home) ->
            val spells = byBook[book].orEmpty().sortedBy { it.first }.map { it.second }
            DevHubTeleportGroup(name, listOf(home) + spells)
        }
    }

    private companion object {
        /** `(spellbook param value, menu label, hand-entered home teleport)` */
        private val SPELLBOOKS =
            listOf(
                Triple(
                    0,
                    "Standard spellbook",
                    DevHubTeleport("Lumbridge Home Teleport", CoordGrid(x = 3222, z = 3218)),
                ),
                Triple(
                    1,
                    "Ancient spellbook",
                    DevHubTeleport("Edgeville Home Teleport", CoordGrid(x = 3087, z = 3496)),
                ),
                Triple(
                    2,
                    "Lunar spellbook",
                    DevHubTeleport("Lunar Home Teleport", CoordGrid(x = 2100, z = 3914)),
                ),
                Triple(
                    3,
                    "Arceuus spellbook",
                    DevHubTeleport("Arceuus Home Teleport", CoordGrid(x = 1712, z = 3882)),
                ),
            )

        private val ITEM_TELEPORTS =
            listOf(
                DevHubTeleportGroup(
                    "Amulet of glory",
                    listOf(
                        DevHubTeleport("Edgeville", CoordGrid(x = 3087, z = 3496)),
                        DevHubTeleport("Karamja", CoordGrid(x = 2918, z = 3176)),
                        DevHubTeleport("Draynor Village", CoordGrid(x = 3105, z = 3251)),
                        DevHubTeleport("Al Kharid", CoordGrid(x = 3293, z = 3163)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Games necklace",
                    listOf(
                        DevHubTeleport("Burthorpe", CoordGrid(x = 2898, z = 3553)),
                        DevHubTeleport("Barbarian Outpost", CoordGrid(x = 2520, z = 3571)),
                        DevHubTeleport("Corporeal Beast", CoordGrid(x = 2966, z = 4382, level = 2)),
                        DevHubTeleport("Wintertodt Camp", CoordGrid(x = 1624, z = 3938)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Ring of dueling",
                    listOf(
                        DevHubTeleport("Emir's Arena", CoordGrid(x = 3316, z = 3235)),
                        DevHubTeleport("Ferox Enclave", CoordGrid(x = 3151, z = 3635)),
                        DevHubTeleport("Castle Wars", CoordGrid(x = 2440, z = 3089)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Ring of wealth",
                    listOf(
                        DevHubTeleport("Grand Exchange", CoordGrid(x = 3164, z = 3487)),
                        DevHubTeleport("Falador Park", CoordGrid(x = 2995, z = 3375)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Combat bracelet",
                    listOf(
                        DevHubTeleport("Warriors' Guild", CoordGrid(x = 2882, z = 3548)),
                        DevHubTeleport("Champions' Guild", CoordGrid(x = 3191, z = 3363)),
                        DevHubTeleport("Monastery", CoordGrid(x = 3052, z = 3488)),
                        DevHubTeleport("Ranging Guild", CoordGrid(x = 2655, z = 3441)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Skills necklace",
                    listOf(
                        DevHubTeleport("Fishing Guild", CoordGrid(x = 2611, z = 3390)),
                        DevHubTeleport("Mining Guild", CoordGrid(x = 3050, z = 9763)),
                        DevHubTeleport("Crafting Guild", CoordGrid(x = 2933, z = 3295)),
                        DevHubTeleport("Cooks' Guild", CoordGrid(x = 3143, z = 3442)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Xeric's talisman",
                    listOf(
                        DevHubTeleport("Xeric's Lookout", CoordGrid(x = 1576, z = 3530)),
                        DevHubTeleport("Xeric's Glade", CoordGrid(x = 1752, z = 3566)),
                        DevHubTeleport("Xeric's Heart", CoordGrid(x = 1504, z = 3817)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Digsite pendant",
                    listOf(
                        DevHubTeleport("Digsite", CoordGrid(x = 3346, z = 3445)),
                        DevHubTeleport("Fossil Island", CoordGrid(x = 3764, z = 3869)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Other items",
                    listOf(
                        DevHubTeleport("Ectofuntus (Ectophial)", CoordGrid(x = 3659, z = 3524)),
                        DevHubTeleport("Grand Tree (Royal seed pod)", CoordGrid(x = 2465, z = 3495)),
                    ),
                ),
            )
    }
}
